### ISSUE TITLE
Updates not happening

### ISSUE THREAD

**Issue by kilrah** [funilrys/aur-urbackup2-server#1]
A comment on https://aur.archlinux.org/packages/urbackup2-server mentions:

> From now on, every change made inside the GitHub repository will be automatically synchronized here.
As of now, every Saturday around 15:30 (UTC); this package would be updated automatically - if a new version is available.

But AUR still serves Urbackup 2.4.15 while 2.5.25 and 2.5.26 have been released in the meantime, could you have a look?
https://www.urbackup.org/server_changelog.html

**Comment by funilrys** [comment]
Thank you for reporting @kilrah, the automation has been fixed.
