### ISSUE TITLE
Download Source

### ISSUE THREAD

**Issue by CrimsonKnight13** [funilrys/aur-urbackup2-server#3]
It looks like the download source path has changed to "https://hndl.urbackup.org/Server/${pkgver}/urbackup-server-${pkgver}.tar.gz"

Without that change, I was unable to build the package.

This also applies to the client package as well.

"https://hndl.urbackup.org/Client/${pkgver}/urbackup-client-${pkgver}.tar.gz"

**Comment by funilrys** [comment]
Hey @CrimsonKnight13, thanks for the notice. Please always feel free to submit a PR to any open-source repository. That's why it's open!
